- description:
  - Plan/review today tasks
  end_time: '22:55'
  id: 88cdec2e-4bcf-403f-8192-bf9978d9ea51
  name: Work planning
  start_time: '22:35'
  tasks:
  - name: Plan and review tasks
    uuid: 59a64c62-ecc4-4241-a5f0-412ca16f08f2
- description: []
  end_time: '23:30'
  id: f88754b7-e846-4a13-ba5c-639a664723e4
  name: New Task
  start_time: '22:55'
  tasks:
  - name: qwe
    uuid: 538e1aff-37b0-4d85-8993-c9ffe5c8c40f
  - name: QQE
    uuid: 75d030ef-b7b3-44e5-87c5-a6b178b81b3f
- description: []
  end_time: '22:35'
  id: aa0aecc3-90bf-47a1-a7ca-b82efc36c2f5
  name: New Task B
  start_time: '22:10'
  tasks:
  - name: B1
    uuid: 3bccaf1e-a3d0-44f2-abb9-5de67b51fc5f
- description:
  - rrrr - more stuff with cool markings
  end_time: 00:00
  id: 47400c85-03a4-4a1f-92e7-e4e26e06efd2
  name: New Task R
  start_time: '23:30'
  tasks: []
